### ISSUE TITLE
Cloudflare static files

### ISSUE THREAD

**Issue by cwagner22** [rphlmr/react-router-hono-server#25]
How to serve static files when using cloudflare worker?
I tried to run the react-router-cloudflare and even here I get 404 for the images.

**Comment by rphlmr** [comment]
👋 I'm working on it for dev

**Comment by cwagner22** [comment]
Anything I can do to help?

**Comment by rphlmr** [comment]
I'm late on the planning because of the WebSocket support on Cloudflare adapter. I had to learn how Durable Objects work.

I'm working on it right now for a builtin support, but you should be able to use Remix Hono helper https://github.com/sergiodxa/remix-hono?tab=readme-ov-file#static-assets-on-cloudflare
It has just been released for RR7

**Comment by cwagner22** [comment]
Thanks, I'm getting `ReferenceError: The binding ASSETS is not set.` but I will probably figure it out...

**Comment by rphlmr** [comment]
Sorry for this bad experience... it's the total opposite of the goal of this library.

You are right, a `ASSETS` binding in Hono `env` is required.
I guess fetch is server.fetch here.
https://github.com/sergiodxa/remix-hono/blob/5beac8d008c220bc0092eb8428fa89fdcd759280/test/cloudflare.test.ts#L30

I will definitely pay attention to this part.

**Comment by rphlmr** [comment]
Ok so the issue is not here.
I have to add a conditional middleware in the adapter in dev mode and remove it on build.

**Comment by cwagner22** [comment]
Thanks.
Unfortunately I'm having terrible performances with Cloudflare worker, even without hono (https://github.com/remix-run/react-router/discussions/12496).
I wanted to compare with aws lambda, but I have to use remix-hono directly. And doing `import * as build from 'build/server'` breaks everything...

**Comment by rphlmr** [comment]
I never used AWS so maybe I'm wrong.
Does it use NodeJS?
With the current temp package (https://pkg.pr.new/rphlmr/react-router-hono-server@24) I return the Hono `app`.
If you follow https://hono.dev/docs/getting-started/aws-lambda it could be:
```ts
import { createHonoServer } from "react-router-hono-server/node";
import { handle } from 'hono/aws-lambda'

const app = await createHonoServer();
export const handler = handle(app);
export default app;
```

**Comment by cwagner22** [comment]
`Could not resolve "virtual:react-router/server-build` unfortunately

**Comment by rphlmr** [comment]
Oh ok, it means that it requires to put a build output and not a ts file to compile.

I don't know how to serve `build/client` files with AWS, but if you need the `build/server` output to be a bundle (one file), you can add this to your Vite config:

```ts
  ssr: {
    target: "webworker",
  },
```

**Comment by rphlmr** [comment]
Version `2.2.0` has been released, so `https://pkg.pr.new/rphlmr/react-router-hono-server@24` is gone 😬

**Comment by diecodev** [comment]
there is a bug when you configure a prerender route:

```ts
import type { Config } from "@react-router/dev/config";

export default {
  // Config options...
  // Server-side render by default, to enable SPA mode set this to `false`
  ssr: true,
  prerender: ["/"], // <- this throw error on build time
} satisfies Config;
```

### Console error
<img width="515" alt="image" src="https://github.com/user-attachments/assets/9326e1a0-d35b-4f4b-a441-fdaec8264c9f" />


> [!NOTE]
> In console says `plugin: 'react-router'` but after remove the `reactRouterHonoServer` from `vite.config.ts` and run `build` command (it means, remove the hono server from build process) the output is correct, a static html is created.
<img width="207" alt="image" src="https://github.com/user-attachments/assets/17d21d53-f095-4059-8dc6-6f296d289bdc" />

**Comment by rphlmr** [comment]
@diecodev is it with Cloudflare?

**Comment by diecodev** [comment]
no, I'm using `createHonoServer` from `"react-router-hono-server/node";`

**Comment by cwagner22** [comment]
For me I'm getting
```
[react-router] Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at groupRoutesByParentId2 (x/node_modules/.pnpm/@react-router+dev@7.0.2_@react-router+serve@7.0.2_react-router@7.0.2_react-dom@19.0.0_react@1_yyc4a7qdc3o3q7j7ib4tun4nl4/node_modules/@react-router/dev/dist/vite.js:2650:10)
    at createPrerenderRoutes (x/node_modules/.pnpm/@react-router+dev@7.0.2_@react-router+serve@7.0.2_react-router@7.0.2_react-dom@19.0.0_react@1_yyc4a7qdc3o3q7j7ib4tun4nl4/node_modules/@react-router/dev/dist/vite.js:2661:76)
 ```
 also with react-router-hono-server/node, not sure if exactly the same error. Without prerender, it fails during requestHandler runtime.

**Comment by diecodev** [comment]
@cwagner22 same:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/cb541f50-a839-4490-851c-9cbeee76a48d" />

**Comment by rphlmr** [comment]
I can reproduce this error too. Not sure what happened here, but I'm looking into it.

**Comment by rphlmr** [comment]
Okay, I found out why.

React Router prerender tries to load build/server/index.js to get the manifest, but at this location, it's the Hono server.

I'm looking for a fix.

**Comment by rphlmr** [comment]
It should be fixed in the next release: https://github.com/rphlmr/react-router-hono-server/pull/37

You can test the preview package with:

```sh
npm i https://pkg.pr.new/rphlmr/react-router-hono-server@37
```

If it's ok, I will release tomorrow!

**Comment by rphlmr** [comment]
It has been released as 2.3.0

Feel free to reopen if cloudflare static is still an issue 🫡

**Comment by cwagner22** [comment]
Unfortunately, while prerender is working, I'm still having the issue at runtime when my lambda function executes:
```
  "TypeError: Cannot convert undefined or null to object",
    "    at Function.values (<anonymous>)",
    "    at groupRoutesByParentId2 (file:///var/task/bundle.mjs:13652:14)",
    "    at createRoutes (file:///var/task/bundle.mjs:13664:71)",
    "    at derive (file:///var/task/bundle.mjs:14043:21)",
    "    at requestHandler (file:///var/task/bundle.mjs:14081:25)",
    "    at Runtime.handler (file:///var/task/bundle.mjs:41222:28)",
    "    at Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1199:38)"
```
I deployed the `with-pre-render` example with `sst`. If you have any tip to debug that... Working without `reactRouterHonoServer()`, and `serverBuildFile` is set.

**Comment by rphlmr** [comment]
@cwagner22 The error is that it tries to import build/server/index.js, which is the Hono server.

I haven’t tried SST but it’s like the react-router.config.ts is not loaded 🧐

**Comment by cwagner22** [comment]
The problem is the sst adapter is using createRequestHandler from react-router, [here](https://github.com/sst/sst/blob/dev/platform/functions/react-server/regional-server.mjs#L104). I thought I could use another adapter such as sst.aws.Router but I'm having other issues.
